### ISSUE TITLE
Should Measure properties be functional?

### ISSUE THREAD

**Issue by rpgoldman** [HajoRijgersberg/OM#53]
As I understand it, the `Measure` gives us a way to pair a unit (`hasDimension`) and a number of those units (`hasNumericalValue`).

Working with Protege, I was surprised to see that nothing seems to enforce `Measure` having only _one_ dimension and _one_ numerical value.  Is this an oversight, or was this a deliberate design decision?

I am not sure whether `hasDimension` and `hasNumericalValue` should be `owl:FunctionalProperty`'s or whether `Measure` should be be restricted to have exactly 1 dimension and one numerical value.  But if some such restriction is not made, doesn't OM admit incoherent models?

**Comment by HajoRijgersberg** [comment]
To be precisely: a Measure has the properties hasUnit and hasNumericalValue.
Thanx for the issue you raised. It's an interesting issue, and I have to think about it.
Originally it was my main objective that OM _facilitates_ functionality rather than restricting. Or, in other words, the first priority was facilitating. Nevertheless, this is an interesting issue. Perhaps also other properties should be defined (or restricted) as functional properties.
In the case of these properties (hasUnit and hasNumericalValue) they could be defined as functional properties.
Let me sleep about it. I think they should be defined as functional properties. I'll come back to this soon, this week is my aim.

**Comment by HajoRijgersberg** [comment]
Yes, I think we should do it. My intention is to define these two properties as functional properties tomorrow, depending on my schedule. I'll keep you updated.

**Comment by HajoRijgersberg** [comment]
I have just uploaded a new version of OM, in which I have defined hasNumericalValue and hasUnit as functional properties. Thanx for the issue!
